"""Generate a module-shaped mkdocstrings reference tree for Zensical.

Zensical derives navigation from the documentation directory hierarchy when no explicit ``nav`` is configured. This generator mirrors ``src/interlens`` under the gitignored ``docs/reference`` directory, giving each Python module a small page containing its mkdocstrings directive without committing mechanical stubs.
"""

import shutil
from pathlib import Path


ROOT = Path(__file__).parents[2]
SOURCE_ROOT = ROOT / "src"
REFERENCE_ROOT = ROOT / "docs" / "reference"
GENERATED_FRONT_MATTER = "---\nhide:\n  - edit\n---\n\n<!-- Generated by scripts/docs/generate_reference.py; do not edit directly. -->\n\n"


def module_parts(source_path: Path) -> tuple[str, ...] | None:
	"""Return the import path represented by a Python source file.

	Args:
		source_path: Python file below the repository's ``src`` directory.

	Returns:
		The module's import-path components, or ``None`` for CLI entrypoints and empty top-level initializers.

	Implementation:
		Package initializers map to their package path so they become section index pages, while ``__main__.py`` files are skipped because they do not expose a useful import API.
	"""
	parts = source_path.relative_to(SOURCE_ROOT).with_suffix("").parts
	if parts[-1] == "__main__":
		return None
	if parts[-1] == "__init__":
		parts = parts[:-1]
	return parts or None


def reference_path(parts: tuple[str, ...]) -> Path:
	"""Return the generated Markdown path for a module.

	Args:
		parts: Components of the module's import path.

	Returns:
		A package ``index.md`` or leaf-module Markdown path below ``docs/reference``.

	Implementation:
		The presence of ``__init__.py`` distinguishes packages from leaf modules and lets Zensical attach package pages directly to their navigation sections.
	"""
	module_source = SOURCE_ROOT.joinpath(*parts)
	if (module_source / "__init__.py").is_file():
		return REFERENCE_ROOT.joinpath(*parts, "index.md")
	return REFERENCE_ROOT.joinpath(*parts).with_suffix(".md")


def generate_reference() -> int:
	"""Replace the generated API reference tree.

	Returns:
		The number of module pages written, excluding the reference landing page.

	Implementation:
		Replacing the owned output directory prevents renamed or deleted modules from leaving stale pages. Generated pages hide their edit action because their source of truth is the corresponding Python module.
	"""
	if REFERENCE_ROOT.exists():
		shutil.rmtree(REFERENCE_ROOT)
	REFERENCE_ROOT.mkdir(parents=True)
	(REFERENCE_ROOT / "index.md").write_text(GENERATED_FRONT_MATTER + "# API reference\n\nThe reference navigation mirrors the Python package and is rendered directly from source docstrings.\n", encoding="utf-8")

	count = 0
	for source_path in sorted(SOURCE_ROOT.rglob("*.py")):
		parts = module_parts(source_path)
		if parts is None:
			continue
		identifier = ".".join(parts)
		page_path = reference_path(parts)
		page_path.parent.mkdir(parents=True, exist_ok=True)
		page_path.write_text(GENERATED_FRONT_MATTER + f"# `{parts[-1]}`\n\n::: {identifier}\n", encoding="utf-8")
		count += 1
	return count


def main() -> None:
	"""Generate the API reference and report the number of module pages."""
	count = generate_reference()
	print(f"Generated {count} API reference pages in {REFERENCE_ROOT.relative_to(ROOT)}")


if __name__ == "__main__":
	main()
