# [rational_agents: grpo-fairness] 2026-08-01 — adapter-directory resolution for AutoModelParticipant.
"""Pointing a participant at a PEFT/LoRA adapter directory resolves its base model and attaches the adapter.

This is what lets a ladder of RL training checkpoints be evaluated through the ordinary "point the runner at a
model" path, instead of merging a full copy of the base weights per checkpoint. No weights are loaded here —
these tests cover the resolution and bookkeeping, which is where a silent mistake (wrong base, adapter dropped,
two adapters batched together) would do real damage to an evaluation.
"""
from __future__ import annotations

import json

import pytest

from interlens import AutoModelParticipant

BASE = "Qwen/Qwen3-8B"


@pytest.fixture
def adapter_dir(tmp_path):
	"""A minimal adapter directory: just the config, which is all the resolution path reads."""
	d = tmp_path / "checkpoint-5"
	d.mkdir()
	(d / "adapter_config.json").write_text(
		json.dumps({"base_model_name_or_path": BASE, "peft_type": "LORA", "r": 32, "lora_alpha": 64}))
	return d


def test_resolves_base_model_and_family_from_the_adapter_config(adapter_dir):
	p = AutoModelParticipant.from_pretrained(str(adapter_dir), name="trained", thinking=False)
	assert p.hf_id == BASE                      # the base is what gets loaded...
	assert p.adapter_path == str(adapter_dir)   # ...with the adapter attached on top
	# The family must come from the BASE config, not be defaulted: a Qwen adapter has to get Qwen's
	# thinking-template handling, or "thinking off" would silently stop being enforced.
	assert type(p).__name__ == "QwenModelParticipant"


def test_adapter_participants_do_not_batch_as_their_base(adapter_dir):
	"""The co-stepper groups participants by ``batch_signature``. If an adapter did not enter the key, a trained
	cell and an untrained one sharing a process would be batched — and silently generated by one of the two."""
	trained = AutoModelParticipant.from_pretrained(str(adapter_dir), name="trained", thinking=False)
	base = AutoModelParticipant.from_pretrained(BASE, name="base", thinking=False)
	assert base.adapter_path is None
	assert trained.batch_signature() != base.batch_signature()


def test_two_different_adapters_are_distinct(adapter_dir, tmp_path):
	other = tmp_path / "checkpoint-20"
	other.mkdir()
	(other / "adapter_config.json").write_text(json.dumps({"base_model_name_or_path": BASE, "peft_type": "LORA"}))
	a = AutoModelParticipant.from_pretrained(str(adapter_dir), name="a", thinking=False)
	b = AutoModelParticipant.from_pretrained(str(other), name="b", thinking=False)
	assert a.batch_signature() != b.batch_signature()


def test_adapter_config_without_a_base_is_a_loud_error(tmp_path):
	d = tmp_path / "broken"
	d.mkdir()
	(d / "adapter_config.json").write_text(json.dumps({"peft_type": "LORA"}))
	with pytest.raises(ValueError, match="base_model_name_or_path"):
		AutoModelParticipant.from_pretrained(str(d), name="broken", thinking=False)


def test_plain_model_ids_are_unaffected():
	p = AutoModelParticipant.from_pretrained(BASE, name="base", thinking=False)
	assert p.hf_id == BASE and p.adapter_path is None
